### PR TITLE
Correcting text in home page

### PR DESCRIPTION
**Pull request by cesarsantostorres2**
Validate changes in text of home page.

### CODE REVIEW

**Review by cesarsantostorres — CHANGES_REQUESTED** [review]
Use html coding for characters representative.

**Comment by cesarsantostorres2** [comment]
Add html representations for typos. Please valid.

**Review by cesarsantostorres — CHANGES_REQUESTED** [review]
The text "Cesar's" don't use accent mark.

**Review by cesarsantostorres — APPROVED** [review]
It's correct! 👍

**Pull request merged**
